#!/bin/bash
switchdir() {
    cd "$(dirname "$0")"
    cd ".."
    cd "bin"
    cd "Holmes.app"
    cd "Contents"
    cd "MacOS"
}

run() {
    question="What basketball team plays at Oracle Arena?"
    answer1="Sacramento Kings"
    answer2="Golden State Warriors"
    answer3="Memphis Grizzlies"

    echo "Enter the question:"
    echo "$question"
    
    echo ""
    echo "Enter the first answer:"
    echo "$answer1"

    echo ""
    echo "Enter the second answer:"
    echo "$answer2"

    echo ""
    echo "Enter the third answer:"
    echo "$answer3"

    ./Holmes "$question" "$answer1" "$answer2" "$answer3"
}

switchdir
run